package Day2;

import java.util.HashMap;

public class part1 {
    private static int pointTotal = 0;
    private static String temper = "";

    private static HashMap<String, Integer> points = new HashMap<String, Integer>();


    public static void main(String args[]){
        setMap();
        calculate();
        System.out.println(pointTotal);
    }

    private static void setMap(){
        points.put("A X", 1+3);
        points.put("A Y", 2+6);
        points.put("A Z", 3);

        points.put("B X", 1);
        points.put("B Y", 2+3);
        points.put("B Z", 3+6);

        points.put("C X", 1+6);
        points.put("C Y", 2);
        points.put("C Z", 3+3);
    }


    private static void calculate(){
        for (int i=0; i < input().length()-1; i++){
            if(i == 0 || input().charAt(i-1) == '\n'){
                temper = input().substring(i, i+3);

                pointTotal += points.get(temper);
            }
        }
    }
    //tie = 3; win = 6

    //rock = A,X 1
    //paper = B,Y 2 
    //scissors = C,Z 3
    private static String input() {
        return "A Z\n" + //
                "A Z\n" + //
                "C Y\n" + //
                "A X\n" + //
                "A X\n" + //
                "A Z\n" + //
                "C X\n" + //
                "A X\n" + //
                "C Y\n" + //
                "A Z\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "C X\n" + //
                "C Y\n" + //
                "C X\n" + //
                "B Y\n" + //
                "A Y\n" + //
                "C Y\n" + //
                "B Y\n" + //
                "B Z\n" + //
                "B Y\n" + //
                "C X\n" + //
                "A Z\n" + //
                "C Y\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "A Z\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "B Z\n" + //
                "B Y\n" + //
                "A Z\n" + //
                "B Y\n" + //
                "C Y\n" + //
                "B Y\n" + //
                "B Z\n" + //
                "C X\n" + //
                "B Z\n" + //
                "A X\n" + //
                "B Y\n" + //
                "B Z\n" + //
                "C Y\n" + //
                "A Z\n" + //
                "C Y\n" + //
                "A Z\n" + //
                "B Y\n" + //
                "C Y\n" + //
                "A Z\n" + //
                "A Z\n" + //
                "B Y\n" + //
                "C Y\n" + //
                "C X\n" + //
                "A Z\n" + //
                "B Z\n" + //
                "A Z\n" + //
                "B Y\n" + //
                "C X\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "A Y\n" + //
                "B Z\n" + //
                "C Y\n" + //
                "C X\n" + //
                "A Z\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "B X\n" + //
                "A Z\n" + //
                "C X\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "A Z\n" + //
                "A Z\n" + //
                "A X\n" + //
                "A X\n" + //
                "B Y\n" + //
                "C X\n" + //
                "A X\n" + //
                "A Z\n" + //
                "A Z\n" + //
                "B Y\n" + //
                "C Y\n" + //
                "B Z\n" + //
                "A X\n" + //
                "B Z\n" + //
                "A Z\n" + //
                "B Y\n" + //
                "A Z\n" + //
                "C Y\n" + //
                "A Z\n" + //
                "A X\n" + //
                "B Y\n" + //
                "C Y\n" + //
                "B Y\n" + //
                "A X\n" + //
                "B Z\n" + //
                "C Y\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "A Z\n" + //
                "A X\n" + //
                "A X\n" + //
                "B Y\n" + //
                "C Y\n" + //
                "B X\n" + //
                "B Z\n" + //
                "C X\n" + //
                "B Y\n" + //
                "A Y\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "A X\n" + //
                "C Y\n" + //
                "A Z\n" + //
                "C Y\n" + //
                "C Y\n" + //
                "B Z\n" + //
                "B Y\n" + //
                "A Z\n" + //
                "A Z\n" + //
                "A Z\n" + //
                "B Y\n" + //
                "C Y\n" + //
                "B Z\n" + //
                "C X\n" + //
                "C Y\n" + //
                "B Z\n" + //
                "A X\n" + //
                "A Z\n" + //
                "C Y\n" + //
                "B Y\n" + //
                "C Y\n" + //
                "C Y\n" + //
                "C Y\n" + //
                "B Y\n" + //
                "B X\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "C Y\n" + //
                "A X\n" + //
                "B Z\n" + //
                "B X\n" + //
                "C X\n" + //
                "B X\n" + //
                "C Y\n" + //
                "B Z\n" + //
                "B Y\n" + //
                "A X\n" + //
                "C Y\n" + //
                "C Y\n" + //
                "C X\n" + //
                "B Z\n" + //
                "B Y\n" + //
                "A Y\n" + //
                "B Z\n" + //
                "A Z\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "B Z\n" + //
                "B Z\n" + //
                "C Y\n" + //
                "A Z\n" + //
                "A X\n" + //
                "A X\n" + //
                "C Y\n" + //
                "B Y\n" + //
                "A Z\n" + //
                "B Z\n" + //
                "A X\n" + //
                "A Z\n" + //
                "B Z\n" + //
                "C Y\n" + //
                "C Z\n" + //
                "A X\n" + //
                "A Y\n" + //
                "B Y\n" + //
                "C Y\n" + //
                "B Y\n" + //
                "C Y\n" + //
                "B Z\n" + //
                "B Y\n" + //
                "A Z\n" + //
                "C Y\n" + //
                "B Z\n" + //
                "B Y\n" + //
                "A Z\n" + //
                "A Y\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "C Y\n" + //
                "A Z\n" + //
                "C Y\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "A X\n" + //
                "A Z\n" + //
                "A Z\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "B Z\n" + //
                "C Y\n" + //
                "C X\n" + //
                "B Z\n" + //
                "A Y\n" + //
                "B Z\n" + //
                "A X\n" + //
                "C X\n" + //
                "A Y\n" + //
                "B Z\n" + //
                "B Z\n" + //
                "A X\n" + //
                "C X\n" + //
                "C X\n" + //
                "A Z\n" + //
                "C Y\n" + //
                "A X\n" + //
                "A X\n" + //
                "C X\n" + //
                "A X\n" + //
                "B Z\n" + //
                "C Z\n" + //
                "B Z\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "A Z\n" + //
                "A Z\n" + //
                "B Y\n" + //
                "A Z\n" + //
                "C Y\n" + //
                "C X\n" + //
                "B Y\n" + //
                "A X\n" + //
                "A X\n" + //
                "B Z\n" + //
                "C Y\n" + //
                "C Y\n" + //
                "A X\n" + //
                "B Z\n" + //
                "A X\n" + //
                "C X\n" + //
                "C X\n" + //
                "B Z\n" + //
                "C X\n" + //
                "B Z\n" + //
                "A X\n" + //
                "A Y\n" + //
                "A X\n" + //
                "A Z\n" + //
                "A X\n" + //
                "B Y\n" + //
                "C Y\n" + //
                "A X\n" + //
                "C Y\n" + //
                "A Z\n" + //
                "B Z\n" + //
                "A Z\n" + //
                "C Y\n" + //
                "A X\n" + //
                "A Z\n" + //
                "B Y\n" + //
                "A Z\n" + //
                "B Z\n" + //
                "B Z\n" + //
                "A Z\n" + //
                "B Z\n" + //
                "A X\n" + //
                "B Y\n" + //
                "B Z\n" + //
                "C X\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "A X\n" + //
                "B Z\n" + //
                "B Z\n" + //
                "A Z\n" + //
                "A Z\n" + //
                "C Y\n" + //
                "B Y\n" + //
                "C X\n" + //
                "A X\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "C X\n" + //
                "B Y\n" + //
                "A X\n" + //
                "C Y\n" + //
                "A Z\n" + //
                "B Y\n" + //
                "A Y\n" + //
                "B Z\n" + //
                "B Y\n" + //
                "A Z\n" + //
                "A X\n" + //
                "B Z\n" + //
                "C Y\n" + //
                "A Z\n" + //
                "C Y\n" + //
                "C X\n" + //
                "B Y\n" + //
                "B Z\n" + //
                "C X\n" + //
                "A Y\n" + //
                "B Z\n" + //
                "A Y\n" + //
                "B Z\n" + //
                "B Z\n" + //
                "B Y\n" + //
                "B Z\n" + //
                "C X\n" + //
                "B Y\n" + //
                "A X\n" + //
                "B Z\n" + //
                "A Z\n" + //
                "B Y\n" + //
                "A Z\n" + //
                "C Y\n" + //
                "C Y\n" + //
                "C X\n" + //
                "C X\n" + //
                "A X\n" + //
                "C X\n" + //
                "A X\n" + //
                "A X\n" + //
                "B Z\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "C X\n" + //
                "C X\n" + //
                "A Z\n" + //
                "A Z\n" + //
                "C X\n" + //
                "C X\n" + //
                "C Y\n" + //
                "C Y\n" + //
                "C Y\n" + //
                "B Y\n" + //
                "A Z\n" + //
                "C Y\n" + //
                "B Z\n" + //
                "B Z\n" + //
                "B Y\n" + //
                "C X\n" + //
                "C X\n" + //
                "C Y\n" + //
                "C Y\n" + //
                "C X\n" + //
                "B Z\n" + //
                "B Z\n" + //
                "B Y\n" + //
                "C Y\n" + //
                "B Y\n" + //
                "A Z\n" + //
                "C Y\n" + //
                "A X\n" + //
                "B Y\n" + //
                "C Y\n" + //
                "C Y\n" + //
                "C Y\n" + //
                "B Y\n" + //
                "A Z\n" + //
                "B Y\n" + //
                "A X\n" + //
                "B Z\n" + //
                "C X\n" + //
                "A Z\n" + //
                "C X\n" + //
                "A Z\n" + //
                "B Z\n" + //
                "C Y\n" + //
                "C Y\n" + //
                "C Y\n" + //
                "C X\n" + //
                "B Z\n" + //
                "C X\n" + //
                "B Y\n" + //
                "B Z\n" + //
                "C X\n" + //
                "B X\n" + //
                "A Z\n" + //
                "B Z\n" + //
                "B Y\n" + //
                "C Y\n" + //
                "B Z\n" + //
                "C Y\n" + //
                "A X\n" + //
                "B Z\n" + //
                "C Y\n" + //
                "C Y\n" + //
                "B Z\n" + //
                "B Y\n" + //
                "C Y\n" + //
                "B Z\n" + //
                "C Y\n" + //
                "A Z\n" + //
                "C X\n" + //
                "C X\n" + //
                "C Y\n" + //
                "A Z\n" + //
                "C Z\n" + //
                "C Y\n" + //
                "B Y\n" + //
                "C Y\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "B Z\n" + //
                "C X\n" + //
                "C X\n" + //
                "B Z\n" + //
                "B Z\n" + //
                "B Z\n" + //
                "A Z\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "A X\n" + //
                "B Y\n" + //
                "C Y\n" + //
                "B Y\n" + //
                "C X\n" + //
                "C X\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "A Y\n" + //
                "B Z\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "C Y\n" + //
                "A Z\n" + //
                "C X\n" + //
                "A Y\n" + //
                "B Y\n" + //
                "B Z\n" + //
                "B Y\n" + //
                "A Y\n" + //
                "C Y\n" + //
                "A Y\n" + //
                "A Z\n" + //
                "B Y\n" + //
                "A Z\n" + //
                "C Y\n" + //
                "C Y\n" + //
                "B Y\n" + //
                "A Z\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "A Z\n" + //
                "B Z\n" + //
                "B Y\n" + //
                "C X\n" + //
                "C Y\n" + //
                "B Z\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "A Z\n" + //
                "C Z\n" + //
                "A Z\n" + //
                "A X\n" + //
                "C X\n" + //
                "B Z\n" + //
                "B Z\n" + //
                "C X\n" + //
                "C Y\n" + //
                "B Y\n" + //
                "B X\n" + //
                "A X\n" + //
                "C Y\n" + //
                "B Z\n" + //
                "B Y\n" + //
                "C X\n" + //
                "B Y\n" + //
                "A Z\n" + //
                "A Z\n" + //
                "A X\n" + //
                "C Y\n" + //
                "B Z\n" + //
                "B Y\n" + //
                "C X\n" + //
                "C X\n" + //
                "B Y\n" + //
                "A Z\n" + //
                "C Z\n" + //
                "B Y\n" + //
                "A Z\n" + //
                "C Y\n" + //
                "B Y\n" + //
                "C X\n" + //
                "A Z\n" + //
                "A Z\n" + //
                "A X\n" + //
                "C X\n" + //
                "A X\n" + //
                "C X\n" + //
                "C X\n" + //
                "A Z\n" + //
                "C X\n" + //
                "B Y\n" + //
                "A Z\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "C Y\n" + //
                "C X\n" + //
                "A Z\n" + //
                "B Z\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "A Y\n" + //
                "A Z\n" + //
                "B Y\n" + //
                "A Z\n" + //
                "B Z\n" + //
                "B Y\n" + //
                "C Y\n" + //
                "A Z\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "C Y\n" + //
                "C X\n" + //
                "A X\n" + //
                "A Z\n" + //
                "B Z\n" + //
                "B Y\n" + //
                "C Y\n" + //
                "B Z\n" + //
                "C X\n" + //
                "B Y\n" + //
                "C X\n" + //
                "A Z\n" + //
                "B Y\n" + //
                "B X\n" + //
                "B Y\n" + //
                "A Y\n" + //
                "A X\n" + //
                "A X\n" + //
                "C X\n" + //
                "C X\n" + //
                "B Y\n" + //
                "B X\n" + //
                "C Y\n" + //
                "A Z\n" + //
                "B Z\n" + //
                "C Y\n" + //
                "C Y\n" + //
                "B Y\n" + //
                "A Z\n" + //
                "C X\n" + //
                "A Z\n" + //
                "C Y\n" + //
                "B Z\n" + //
                "B X\n" + //
                "C X\n" + //
                "B X\n" + //
                "C X\n" + //
                "B Y\n" + //
                "C Y\n" + //
                "C Y\n" + //
                "B Z\n" + //
                "B Y\n" + //
                "B Z\n" + //
                "B Z\n" + //
                "A Z\n" + //
                "B Y\n" + //
                "A Y\n" + //
                "B Z\n" + //
                "C X\n" + //
                "C Y\n" + //
                "C X\n" + //
                "A Z\n" + //
                "B Z\n" + //
                "C Y\n" + //
                "B Y\n" + //
                "B Z\n" + //
                "C X\n" + //
                "B Y\n" + //
                "A Y\n" + //
                "A X\n" + //
                "A X\n" + //
                "C Y\n" + //
                "B X\n" + //
                "C X\n" + //
                "B Z\n" + //
                "A Z\n" + //
                "A Y\n" + //
                "B Z\n" + //
                "C X\n" + //
                "C X\n" + //
                "B Y\n" + //
                "A X\n" + //
                "B Z\n" + //
                "C Y\n" + //
                "B X\n" + //
                "B Z\n" + //
                "C Y\n" + //
                "B Y\n" + //
                "C Y\n" + //
                "B Z\n" + //
                "B Y\n" + //
                "B Z\n" + //
                "B Y\n" + //
                "C X\n" + //
                "B Y\n" + //
                "C X\n" + //
                "B Z\n" + //
                "B Z\n" + //
                "C X\n" + //
                "B Z\n" + //
                "A X\n" + //
                "B X\n" + //
                "B Y\n" + //
                "A X\n" + //
                "B Z\n" + //
                "C X\n" + //
                "B Z\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "C X\n" + //
                "A Y\n" + //
                "B Z\n" + //
                "B Z\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "B Z\n" + //
                "C Y\n" + //
                "B Z\n" + //
                "C Y\n" + //
                "C X\n" + //
                "A Z\n" + //
                "C X\n" + //
                "A X\n" + //
                "C Y\n" + //
                "B Y\n" + //
                "C X\n" + //
                "A Z\n" + //
                "B Y\n" + //
                "A Z\n" + //
                "A Z\n" + //
                "B X\n" + //
                "C Y\n" + //
                "B Z\n" + //
                "C Y\n" + //
                "B Y\n" + //
                "B Z\n" + //
                "A X\n" + //
                "B Z\n" + //
                "A X\n" + //
                "C X\n" + //
                "B Z\n" + //
                "B Y\n" + //
                "C X\n" + //
                "C Y\n" + //
                "C Y\n" + //
                "B X\n" + //
                "C X\n" + //
                "C X\n" + //
                "B Z\n" + //
                "C Y\n" + //
                "B Z\n" + //
                "B Y\n" + //
                "B Z\n" + //
                "C Y\n" + //
                "B Y\n" + //
                "C Y\n" + //
                "C X\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "B Z\n" + //
                "A Z\n" + //
                "C X\n" + //
                "A Z\n" + //
                "B Y\n" + //
                "B Z\n" + //
                "A Z\n" + //
                "C Y\n" + //
                "A Z\n" + //
                "B Y\n" + //
                "A Z\n" + //
                "A Z\n" + //
                "C Y\n" + //
                "A Y\n" + //
                "B Y\n" + //
                "A Y\n" + //
                "C X\n" + //
                "B Y\n" + //
                "C X\n" + //
                "B Z\n" + //
                "C Y\n" + //
                "A Z\n" + //
                "C X\n" + //
                "C X\n" + //
                "B Z\n" + //
                "C Z\n" + //
                "C Z\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "C Y\n" + //
                "C Y\n" + //
                "A Z\n" + //
                "C Y\n" + //
                "C Y\n" + //
                "C Y\n" + //
                "A Z\n" + //
                "B Z\n" + //
                "C Y\n" + //
                "B Y\n" + //
                "C Y\n" + //
                "C X\n" + //
                "C X\n" + //
                "B X\n" + //
                "B Y\n" + //
                "C Y\n" + //
                "A Y\n" + //
                "B Y\n" + //
                "B Z\n" + //
                "B Y\n" + //
                "A Y\n" + //
                "B Y\n" + //
                "B X\n" + //
                "C X\n" + //
                "C Z\n" + //
                "C Y\n" + //
                "C Y\n" + //
                "C Y\n" + //
                "B Z\n" + //
                "B X\n" + //
                "C Y\n" + //
                "B Z\n" + //
                "C X\n" + //
                "C Y\n" + //
                "A Z\n" + //
                "A Y\n" + //
                "B Y\n" + //
                "C X\n" + //
                "A Z\n" + //
                "B Y\n" + //
                "C Y\n" + //
                "B Z\n" + //
                "A Z\n" + //
                "A Z\n" + //
                "B Y\n" + //
                "A Z\n" + //
                "C Y\n" + //
                "A X\n" + //
                "C Y\n" + //
                "B Z\n" + //
                "B Z\n" + //
                "B Z\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "A Z\n" + //
                "A Z\n" + //
                "B Y\n" + //
                "C X\n" + //
                "A Z\n" + //
                "C Y\n" + //
                "B Y\n" + //
                "A Z\n" + //
                "C Y\n" + //
                "A Z\n" + //
                "B Z\n" + //
                "B Z\n" + //
                "A Y\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "B Z\n" + //
                "C Z\n" + //
                "B Y\n" + //
                "B X\n" + //
                "B Y\n" + //
                "C X\n" + //
                "B Z\n" + //
                "C Y\n" + //
                "B Z\n" + //
                "A Y\n" + //
                "B Z\n" + //
                "A Z\n" + //
                "A X\n" + //
                "A Z\n" + //
                "C X\n" + //
                "C X\n" + //
                "B Y\n" + //
                "C X\n" + //
                "C Y\n" + //
                "A Z\n" + //
                "B Z\n" + //
                "B Y\n" + //
                "A Z\n" + //
                "B Z\n" + //
                "B Z\n" + //
                "B Z\n" + //
                "C Y\n" + //
                "B Y\n" + //
                "A X\n" + //
                "C Y\n" + //
                "C Y\n" + //
                "C X\n" + //
                "A X\n" + //
                "C Y\n" + //
                "B Y\n" + //
                "C X\n" + //
                "B Z\n" + //
                "A Y\n" + //
                "B X\n" + //
                "B Y\n" + //
                "A Z\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "B Z\n" + //
                "C X\n" + //
                "B Z\n" + //
                "B Z\n" + //
                "C X\n" + //
                "B Y\n" + //
                "A Y\n" + //
                "B Y\n" + //
                "C Y\n" + //
                "A Z\n" + //
                "C Z\n" + //
                "B Y\n" + //
                "B Z\n" + //
                "B Z\n" + //
                "C Y\n" + //
                "A Z\n" + //
                "C Y\n" + //
                "C X\n" + //
                "C Y\n" + //
                "B Y\n" + //
                "A X\n" + //
                "A X\n" + //
                "B Z\n" + //
                "C Y\n" + //
                "B Z\n" + //
                "B Y\n" + //
                "A Y\n" + //
                "C X\n" + //
                "A Z\n" + //
                "B Z\n" + //
                "C Y\n" + //
                "C Z\n" + //
                "C X\n" + //
                "B Y\n" + //
                "C X\n" + //
                "A Y\n" + //
                "A Y\n" + //
                "B Z\n" + //
                "C X\n" + //
                "B X\n" + //
                "C X\n" + //
                "B Y\n" + //
                "B Z\n" + //
                "B Z\n" + //
                "B Y\n" + //
                "C Y\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "A Z\n" + //
                "B Z\n" + //
                "B Y\n" + //
                "C X\n" + //
                "B Z\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "C Y\n" + //
                "C Z\n" + //
                "C X\n" + //
                "B Y\n" + //
                "A X\n" + //
                "C Y\n" + //
                "C X\n" + //
                "B Z\n" + //
                "C Y\n" + //
                "A X\n" + //
                "B Y\n" + //
                "A Y\n" + //
                "B Y\n" + //
                "C X\n" + //
                "C Y\n" + //
                "C X\n" + //
                "A X\n" + //
                "B Z\n" + //
                "C X\n" + //
                "B Y\n" + //
                "A Z\n" + //
                "C X\n" + //
                "B Y\n" + //
                "A Z\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "A Z\n" + //
                "A X\n" + //
                "C X\n" + //
                "C Y\n" + //
                "C Y\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "B Z\n" + //
                "A Y\n" + //
                "C X\n" + //
                "C X\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "B Z\n" + //
                "A X\n" + //
                "C X\n" + //
                "C X\n" + //
                "B X\n" + //
                "A X\n" + //
                "B Z\n" + //
                "B Y\n" + //
                "C X\n" + //
                "A X\n" + //
                "B Y\n" + //
                "C Y\n" + //
                "A X\n" + //
                "B Y\n" + //
                "C X\n" + //
                "B Z\n" + //
                "C Z\n" + //
                "B X\n" + //
                "C Y\n" + //
                "B Y\n" + //
                "C Y\n" + //
                "A Z\n" + //
                "C Y\n" + //
                "B Z\n" + //
                "C X\n" + //
                "B Z\n" + //
                "C X\n" + //
                "C Y\n" + //
                "C X\n" + //
                "C Y\n" + //
                "C Z\n" + //
                "C X\n" + //
                "C X\n" + //
                "B Y\n" + //
                "C Y\n" + //
                "C X\n" + //
                "C X\n" + //
                "B Z\n" + //
                "B Z\n" + //
                "A X\n" + //
                "C Y\n" + //
                "C Z\n" + //
                "B Y\n" + //
                "C Z\n" + //
                "C Y\n" + //
                "C X\n" + //
                "C X\n" + //
                "B Y\n" + //
                "C Y\n" + //
                "A Y\n" + //
                "B Y\n" + //
                "A Y\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "C Y\n" + //
                "C Z\n" + //
                "B Y\n" + //
                "C X\n" + //
                "C X\n" + //
                "B Z\n" + //
                "B Y\n" + //
                "B Z\n" + //
                "C Y\n" + //
                "B Z\n" + //
                "C X\n" + //
                "B Z\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "A Z\n" + //
                "A X\n" + //
                "B X\n" + //
                "A X\n" + //
                "C X\n" + //
                "C Y\n" + //
                "B Y\n" + //
                "A X\n" + //
                "B Z\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "A X\n" + //
                "C X\n" + //
                "C X\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "C Y\n" + //
                "C Y\n" + //
                "B Z\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "C Y\n" + //
                "A X\n" + //
                "B Y\n" + //
                "C Y\n" + //
                "B Z\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "B Z\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "B Z\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "C Y\n" + //
                "A Z\n" + //
                "B Z\n" + //
                "A Y\n" + //
                "B Y\n" + //
                "C Y\n" + //
                "B Z\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "C X\n" + //
                "A X\n" + //
                "C Z\n" + //
                "C X\n" + //
                "B Y\n" + //
                "B Z\n" + //
                "C Y\n" + //
                "C X\n" + //
                "B Z\n" + //
                "A Z\n" + //
                "A Z\n" + //
                "C Y\n" + //
                "A Z\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "B Z\n" + //
                "B Y\n" + //
                "C Y\n" + //
                "B Z\n" + //
                "C Y\n" + //
                "B Z\n" + //
                "B Z\n" + //
                "B Y\n" + //
                "C X\n" + //
                "B Y\n" + //
                "B Z\n" + //
                "A X\n" + //
                "C X\n" + //
                "C X\n" + //
                "B Z\n" + //
                "B Z\n" + //
                "C X\n" + //
                "B Y\n" + //
                "A Z\n" + //
                "B Y\n" + //
                "B Z\n" + //
                "C Y\n" + //
                "B Y\n" + //
                "A Z\n" + //
                "B Z\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "C X\n" + //
                "C Y\n" + //
                "A Z\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "A Z\n" + //
                "A Z\n" + //
                "A Z\n" + //
                "A X\n" + //
                "B X\n" + //
                "A Z\n" + //
                "C Y\n" + //
                "C X\n" + //
                "A X\n" + //
                "B Z\n" + //
                "A X\n" + //
                "C X\n" + //
                "B Z\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "C X\n" + //
                "A Z\n" + //
                "C Y\n" + //
                "C X\n" + //
                "A Y\n" + //
                "C X\n" + //
                "A Z\n" + //
                "B Z\n" + //
                "B Z\n" + //
                "B Y\n" + //
                "C Y\n" + //
                "B Z\n" + //
                "A Z\n" + //
                "A Z\n" + //
                "C Y\n" + //
                "B Y\n" + //
                "B Z\n" + //
                "A Z\n" + //
                "A Z\n" + //
                "B Z\n" + //
                "B Y\n" + //
                "A Z\n" + //
                "C Y\n" + //
                "A Z\n" + //
                "A Z\n" + //
                "B Y\n" + //
                "B Z\n" + //
                "B Z\n" + //
                "A X\n" + //
                "A X\n" + //
                "B Y\n" + //
                "B Z\n" + //
                "B Z\n" + //
                "C X\n" + //
                "B Z\n" + //
                "C Z\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "B Z\n" + //
                "A X\n" + //
                "A Z\n" + //
                "B Y\n" + //
                "A X\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "C X\n" + //
                "C X\n" + //
                "C Y\n" + //
                "C Y\n" + //
                "A Z\n" + //
                "A X\n" + //
                "B Y\n" + //
                "A Z\n" + //
                "B Z\n" + //
                "B Y\n" + //
                "C X\n" + //
                "B Y\n" + //
                "B X\n" + //
                "C X\n" + //
                "A X\n" + //
                "A Z\n" + //
                "C Y\n" + //
                "C X\n" + //
                "C Y\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "A X\n" + //
                "A Y\n" + //
                "B Y\n" + //
                "A Y\n" + //
                "C Y\n" + //
                "C X\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "B Z\n" + //
                "C X\n" + //
                "C X\n" + //
                "B Y\n" + //
                "C X\n" + //
                "B Z\n" + //
                "C Y\n" + //
                "A X\n" + //
                "A Z\n" + //
                "A Z\n" + //
                "B Y\n" + //
                "A Y\n" + //
                "C Y\n" + //
                "C X\n" + //
                "C Y\n" + //
                "C Y\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "A Z\n" + //
                "C X\n" + //
                "A X\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "B Z\n" + //
                "A Z\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "A Z\n" + //
                "B Y\n" + //
                "A Z\n" + //
                "C X\n" + //
                "B Z\n" + //
                "C Y\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "A X\n" + //
                "B Y\n" + //
                "A X\n" + //
                "B Y\n" + //
                "B Z\n" + //
                "C X\n" + //
                "B Z\n" + //
                "B Y\n" + //
                "C X\n" + //
                "C Y\n" + //
                "C Y\n" + //
                "A X\n" + //
                "A X\n" + //
                "B Z\n" + //
                "B Z\n" + //
                "B Y\n" + //
                "C X\n" + //
                "A Z\n" + //
                "C Y\n" + //
                "C Y\n" + //
                "C Y\n" + //
                "B Z\n" + //
                "B Z\n" + //
                "B Y\n" + //
                "A Z\n" + //
                "C Y\n" + //
                "A X\n" + //
                "A Z\n" + //
                "C Y\n" + //
                "B Z\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "A Z\n" + //
                "B Y\n" + //
                "A Z\n" + //
                "C X\n" + //
                "A X\n" + //
                "B Z\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "B Z\n" + //
                "A Z\n" + //
                "C X\n" + //
                "B Y\n" + //
                "C X\n" + //
                "B Z\n" + //
                "C X\n" + //
                "A Z\n" + //
                "B Y\n" + //
                "A Z\n" + //
                "A Z\n" + //
                "B Y\n" + //
                "C Y\n" + //
                "C X\n" + //
                "C Y\n" + //
                "A X\n" + //
                "C Y\n" + //
                "B Y\n" + //
                "B Z\n" + //
                "C X\n" + //
                "C Y\n" + //
                "A X\n" + //
                "B Z\n" + //
                "B Y\n" + //
                "C Y\n" + //
                "A X\n" + //
                "B Z\n" + //
                "A Y\n" + //
                "B Z\n" + //
                "B Y\n" + //
                "B Z\n" + //
                "A X\n" + //
                "A Z\n" + //
                "A X\n" + //
                "B Z\n" + //
                "C Y\n" + //
                "B Y\n" + //
                "A Y\n" + //
                "B Z\n" + //
                "A Z\n" + //
                "C Y\n" + //
                "C X\n" + //
                "B Z\n" + //
                "B Y\n" + //
                "C Y\n" + //
                "B Z\n" + //
                "C X\n" + //
                "C Y\n" + //
                "A X\n" + //
                "B Z\n" + //
                "B Z\n" + //
                "B Z\n" + //
                "B Z\n" + //
                "B Y\n" + //
                "C X\n" + //
                "B Y\n" + //
                "C X\n" + //
                "A Z\n" + //
                "A Z\n" + //
                "C Y\n" + //
                "A Y\n" + //
                "B Y\n" + //
                "C X\n" + //
                "A Z\n" + //
                "B Z\n" + //
                "C X\n" + //
                "C X\n" + //
                "A X\n" + //
                "B Y\n" + //
                "C X\n" + //
                "A Z\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "C X\n" + //
                "C Y\n" + //
                "C Y\n" + //
                "B Y\n" + //
                "A Z\n" + //
                "B Y\n" + //
                "B Z\n" + //
                "B Z\n" + //
                "B Y\n" + //
                "A X\n" + //
                "B Z\n" + //
                "B Z\n" + //
                "C X\n" + //
                "C X\n" + //
                "C Y\n" + //
                "B Y\n" + //
                "C Y\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "B Z\n" + //
                "B X\n" + //
                "C X\n" + //
                "C Y\n" + //
                "A Z\n" + //
                "B Z\n" + //
                "B Y\n" + //
                "A X\n" + //
                "B Z\n" + //
                "A Z\n" + //
                "B Z\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "A Z\n" + //
                "C Y\n" + //
                "B Y\n" + //
                "C Y\n" + //
                "B Z\n" + //
                "B Y\n" + //
                "C X\n" + //
                "B Z\n" + //
                "B Z\n" + //
                "C Y\n" + //
                "C Y\n" + //
                "B Y\n" + //
                "C Y\n" + //
                "C X\n" + //
                "B X\n" + //
                "B Y\n" + //
                "C Y\n" + //
                "B Y\n" + //
                "B X\n" + //
                "C X\n" + //
                "B Y\n" + //
                "A Y\n" + //
                "A Z\n" + //
                "A Y\n" + //
                "B Z\n" + //
                "A Z\n" + //
                "A Z\n" + //
                "A Z\n" + //
                "B Y\n" + //
                "A Z\n" + //
                "A Z\n" + //
                "C Y\n" + //
                "B Z\n" + //
                "A Z\n" + //
                "A X\n" + //
                "B Y\n" + //
                "C Y\n" + //
                "C X\n" + //
                "C X\n" + //
                "A Z\n" + //
                "B Z\n" + //
                "B X\n" + //
                "B Z\n" + //
                "C X\n" + //
                "B Z\n" + //
                "C Y\n" + //
                "C X\n" + //
                "C Z\n" + //
                "C X\n" + //
                "B Z\n" + //
                "B Z\n" + //
                "B Z\n" + //
                "B Z\n" + //
                "A Z\n" + //
                "A Z\n" + //
                "C Y\n" + //
                "C Z\n" + //
                "C Y\n" + //
                "A X\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "A Z\n" + //
                "A Z\n" + //
                "B Z\n" + //
                "C Y\n" + //
                "C X\n" + //
                "B Y\n" + //
                "C X\n" + //
                "B Z\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "B X\n" + //
                "A Z\n" + //
                "A X\n" + //
                "A Y\n" + //
                "C X\n" + //
                "B Z\n" + //
                "B Y\n" + //
                "B Z\n" + //
                "C Y\n" + //
                "A Z\n" + //
                "B Z\n" + //
                "B Z\n" + //
                "C Y\n" + //
                "B Z\n" + //
                "B Z\n" + //
                "C X\n" + //
                "B Y\n" + //
                "C X\n" + //
                "B Z\n" + //
                "C X\n" + //
                "C Y\n" + //
                "C Y\n" + //
                "C X\n" + //
                "A Z\n" + //
                "A Z\n" + //
                "B Z\n" + //
                "B Y\n" + //
                "C X\n" + //
                "C X\n" + //
                "A Y\n" + //
                "A Z\n" + //
                "C X\n" + //
                "A X\n" + //
                "A X\n" + //
                "A Z\n" + //
                "C Y\n" + //
                "B Z\n" + //
                "B Y\n" + //
                "A Z\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "B Z\n" + //
                "B Y\n" + //
                "C Y\n" + //
                "B Z\n" + //
                "A X\n" + //
                "B Y\n" + //
                "A X\n" + //
                "B Z\n" + //
                "A Z\n" + //
                "C X\n" + //
                "A X\n" + //
                "C Z\n" + //
                "A Z\n" + //
                "C Y\n" + //
                "A X\n" + //
                "B Y\n" + //
                "B Z\n" + //
                "B Z\n" + //
                "A X\n" + //
                "C Y\n" + //
                "A Z\n" + //
                "C X\n" + //
                "A Y\n" + //
                "C X\n" + //
                "B Y\n" + //
                "B Z\n" + //
                "A X\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "A Y\n" + //
                "A X\n" + //
                "B Y\n" + //
                "C X\n" + //
                "A Y\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "C Y\n" + //
                "A Z\n" + //
                "B Z\n" + //
                "A Z\n" + //
                "B Y\n" + //
                "A Z\n" + //
                "C Y\n" + //
                "C X\n" + //
                "B Z\n" + //
                "B Y\n" + //
                "B Z\n" + //
                "A X\n" + //
                "C Y\n" + //
                "C Z\n" + //
                "A X\n" + //
                "A X\n" + //
                "C Y\n" + //
                "C Y\n" + //
                "A Z\n" + //
                "C Y\n" + //
                "C X\n" + //
                "A Y\n" + //
                "C Y\n" + //
                "B Y\n" + //
                "B X\n" + //
                "B Y\n" + //
                "A Z\n" + //
                "C X\n" + //
                "C X\n" + //
                "B Y\n" + //
                "A Z\n" + //
                "A X\n" + //
                "B Z\n" + //
                "C X\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "C Z\n" + //
                "A X\n" + //
                "A X\n" + //
                "B Z\n" + //
                "C X\n" + //
                "C Y\n" + //
                "B Z\n" + //
                "C Z\n" + //
                "B Y\n" + //
                "A Y\n" + //
                "A Z\n" + //
                "A Y\n" + //
                "C Y\n" + //
                "C Y\n" + //
                "C Y\n" + //
                "B Z\n" + //
                "B Z\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "B Z\n" + //
                "B Z\n" + //
                "C X\n" + //
                "A X\n" + //
                "C X\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "C Y\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "C X\n" + //
                "A Y\n" + //
                "B Z\n" + //
                "C X\n" + //
                "B Z\n" + //
                "B Y\n" + //
                "A X\n" + //
                "C Y\n" + //
                "B Y\n" + //
                "C Y\n" + //
                "B Z\n" + //
                "B Y\n" + //
                "C Y\n" + //
                "C Z\n" + //
                "C Y\n" + //
                "A Y\n" + //
                "B Z\n" + //
                "A X\n" + //
                "B Z\n" + //
                "A Z\n" + //
                "A Z\n" + //
                "A Z\n" + //
                "B Y\n" + //
                "A X\n" + //
                "C Y\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "C X\n" + //
                "B Y\n" + //
                "A X\n" + //
                "C X\n" + //
                "B Y\n" + //
                "C X\n" + //
                "A Z\n" + //
                "B Z\n" + //
                "B Z\n" + //
                "B Y\n" + //
                "C Y\n" + //
                "B Y\n" + //
                "A Z\n" + //
                "B Y\n" + //
                "C Y\n" + //
                "B Z\n" + //
                "C X\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "B Z\n" + //
                "C X\n" + //
                "C Y\n" + //
                "B Z\n" + //
                "B Z\n" + //
                "C Y\n" + //
                "C X\n" + //
                "C X\n" + //
                "B Y\n" + //
                "B Z\n" + //
                "A X\n" + //
                "C X\n" + //
                "A Z\n" + //
                "A Y\n" + //
                "B Z\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "C Y\n" + //
                "C X\n" + //
                "B Y\n" + //
                "B Z\n" + //
                "C Y\n" + //
                "C Y\n" + //
                "C X\n" + //
                "C X\n" + //
                "B Z\n" + //
                "A Z\n" + //
                "B Z\n" + //
                "B Y\n" + //
                "C X\n" + //
                "A X\n" + //
                "C X\n" + //
                "A Z\n" + //
                "C X\n" + //
                "B Z\n" + //
                "C Z\n" + //
                "B Y\n" + //
                "C Y\n" + //
                "B Y\n" + //
                "C Z\n" + //
                "A Z\n" + //
                "B Y\n" + //
                "C Z\n" + //
                "A X\n" + //
                "B Z\n" + //
                "B X\n" + //
                "C Y\n" + //
                "C X\n" + //
                "B Z\n" + //
                "A Z\n" + //
                "B Y\n" + //
                "A X\n" + //
                "B X\n" + //
                "A Z\n" + //
                "C Y\n" + //
                "A Y\n" + //
                "A Z\n" + //
                "A X\n" + //
                "C X\n" + //
                "A Y\n" + //
                "C X\n" + //
                "B X\n" + //
                "B Y\n" + //
                "C Z\n" + //
                "A Z\n" + //
                "C X\n" + //
                "B Y\n" + //
                "C X\n" + //
                "C X\n" + //
                "B X\n" + //
                "B Y\n" + //
                "A Y\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "A Z\n" + //
                "B Y\n" + //
                "C Y\n" + //
                "C X\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "B Z\n" + //
                "C Y\n" + //
                "B Z\n" + //
                "A Z\n" + //
                "A Z\n" + //
                "A X\n" + //
                "B Y\n" + //
                "C Y\n" + //
                "B Y\n" + //
                "C Y\n" + //
                "C Y\n" + //
                "B Z\n" + //
                "A X\n" + //
                "C Y\n" + //
                "B Z\n" + //
                "C Y\n" + //
                "A Y\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "C Y\n" + //
                "A Z\n" + //
                "A Z\n" + //
                "B Z\n" + //
                "A Z\n" + //
                "C Y\n" + //
                "C Y\n" + //
                "B Y\n" + //
                "C X\n" + //
                "B Y\n" + //
                "A Z\n" + //
                "B Z\n" + //
                "A X\n" + //
                "B Z\n" + //
                "B Y\n" + //
                "B Z\n" + //
                "A X\n" + //
                "A X\n" + //
                "C Y\n" + //
                "A Z\n" + //
                "B Z\n" + //
                "C Y\n" + //
                "B Z\n" + //
                "C X\n" + //
                "B Z\n" + //
                "A X\n" + //
                "B Z\n" + //
                "B Z\n" + //
                "C Y\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "C Y\n" + //
                "B Y\n" + //
                "A X\n" + //
                "B Y\n" + //
                "C Y\n" + //
                "A Z\n" + //
                "B Y\n" + //
                "C X\n" + //
                "A Z\n" + //
                "B Z\n" + //
                "A Z\n" + //
                "B Z\n" + //
                "C Y\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "C Y\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "A Z\n" + //
                "B Y\n" + //
                "B Z\n" + //
                "C X\n" + //
                "B Z\n" + //
                "C X\n" + //
                "C X\n" + //
                "A X\n" + //
                "B Z\n" + //
                "C Z\n" + //
                "B Z\n" + //
                "A Y\n" + //
                "C X\n" + //
                "C X\n" + //
                "A Z\n" + //
                "A X\n" + //
                "A Y\n" + //
                "A X\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "C X\n" + //
                "C Z\n" + //
                "A Y\n" + //
                "C Y\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "C X\n" + //
                "C X\n" + //
                "B Z\n" + //
                "B Z\n" + //
                "B Y\n" + //
                "C Y\n" + //
                "A Z\n" + //
                "B Y\n" + //
                "C X\n" + //
                "C X\n" + //
                "A X\n" + //
                "A X\n" + //
                "A Y\n" + //
                "B Y\n" + //
                "C X\n" + //
                "A Z\n" + //
                "C Z\n" + //
                "C Y\n" + //
                "C Y\n" + //
                "C Y\n" + //
                "B Y\n" + //
                "C Y\n" + //
                "A Y\n" + //
                "A X\n" + //
                "B X\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "A Z\n" + //
                "B Z\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "C Y\n" + //
                "A X\n" + //
                "A Z\n" + //
                "A Z\n" + //
                "A Z\n" + //
                "B Y\n" + //
                "A X\n" + //
                "C Y\n" + //
                "C Y\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "C Y\n" + //
                "A Z\n" + //
                "C Y\n" + //
                "A X\n" + //
                "C X\n" + //
                "B Z\n" + //
                "B Y\n" + //
                "C X\n" + //
                "B Y\n" + //
                "A X\n" + //
                "A Z\n" + //
                "C X\n" + //
                "C Y\n" + //
                "C Y\n" + //
                "C X\n" + //
                "C X\n" + //
                "B Z\n" + //
                "B Y\n" + //
                "A Z\n" + //
                "B Y\n" + //
                "B Z\n" + //
                "B Z\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "A X\n" + //
                "C X\n" + //
                "C Y\n" + //
                "C X\n" + //
                "A Z\n" + //
                "B Z\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "C Y\n" + //
                "A X\n" + //
                "A X\n" + //
                "C Y\n" + //
                "C X\n" + //
                "B Z\n" + //
                "A Y\n" + //
                "B Y\n" + //
                "B Z\n" + //
                "B Y\n" + //
                "A X\n" + //
                "C Y\n" + //
                "B Y\n" + //
                "A X\n" + //
                "C X\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "A Z\n" + //
                "A Z\n" + //
                "A Z\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "C X\n" + //
                "B Z\n" + //
                "A Z\n" + //
                "B Z\n" + //
                "A Z\n" + //
                "C X\n" + //
                "B Y\n" + //
                "C X\n" + //
                "B Y\n" + //
                "C X\n" + //
                "C X\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "A Y\n" + //
                "C Y\n" + //
                "C Y\n" + //
                "B Z\n" + //
                "C X\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "A X\n" + //
                "A Z\n" + //
                "B Y\n" + //
                "C Y\n" + //
                "B Y\n" + //
                "C Y\n" + //
                "A X\n" + //
                "C Y\n" + //
                "C Y\n" + //
                "B Z\n" + //
                "C Y\n" + //
                "A X\n" + //
                "C X\n" + //
                "A Z\n" + //
                "C Y\n" + //
                "A Z\n" + //
                "C X\n" + //
                "B Z\n" + //
                "B Y\n" + //
                "B Z\n" + //
                "C Y\n" + //
                "B X\n" + //
                "A Z\n" + //
                "C Y\n" + //
                "C X\n" + //
                "B Y\n" + //
                "C X\n" + //
                "B Z\n" + //
                "A X\n" + //
                "A Z\n" + //
                "C X\n" + //
                "B Z\n" + //
                "C X\n" + //
                "B Y\n" + //
                "A Z\n" + //
                "B Y\n" + //
                "C Y\n" + //
                "B Y\n" + //
                "C X\n" + //
                "C Y\n" + //
                "B X\n" + //
                "B X\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "B Z\n" + //
                "B Y\n" + //
                "C X\n" + //
                "A Z\n" + //
                "A Z\n" + //
                "C X\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "A Y\n" + //
                "C Y\n" + //
                "B Z\n" + //
                "C X\n" + //
                "C Y\n" + //
                "A X\n" + //
                "C Y\n" + //
                "B Z\n" + //
                "C Y\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "B Z\n" + //
                "A Z\n" + //
                "A Z\n" + //
                "B Y\n" + //
                "A Y\n" + //
                "B Z\n" + //
                "A X\n" + //
                "C Y\n" + //
                "B Y\n" + //
                "A X\n" + //
                "C X\n" + //
                "B Y\n" + //
                "C Y\n" + //
                "B Z\n" + //
                "B Y\n" + //
                "C X\n" + //
                "A Z\n" + //
                "C Y\n" + //
                "A Z\n" + //
                "B Y\n" + //
                "C Y\n" + //
                "B Y\n" + //
                "C X\n" + //
                "A Z\n" + //
                "C Y\n" + //
                "C Y\n" + //
                "A Y\n" + //
                "B Z\n" + //
                "C X\n" + //
                "C X\n" + //
                "A Z\n" + //
                "C Z\n" + //
                "C X\n" + //
                "B Y\n" + //
                "C X\n" + //
                "A X\n" + //
                "C Y\n" + //
                "C X\n" + //
                "C X\n" + //
                "A X\n" + //
                "A Y\n" + //
                "A X\n" + //
                "C X\n" + //
                "A X\n" + //
                "A X\n" + //
                "B X\n" + //
                "B Y\n" + //
                "C Y\n" + //
                "A X\n" + //
                "B Z\n" + //
                "C X\n" + //
                "C Y\n" + //
                "B Y\n" + //
                "B Z\n" + //
                "C Y\n" + //
                "B Z\n" + //
                "B Y\n" + //
                "C X\n" + //
                "A X\n" + //
                "B Y\n" + //
                "B Z\n" + //
                "C Y\n" + //
                "A Z\n" + //
                "C X\n" + //
                "C Z\n" + //
                "A X\n" + //
                "A Z\n" + //
                "A Z\n" + //
                "B Z\n" + //
                "A Z\n" + //
                "B Y\n" + //
                "C Y\n" + //
                "C Y\n" + //
                "B Z\n" + //
                "C Y\n" + //
                "C Y\n" + //
                "C Y\n" + //
                "C X\n" + //
                "A X\n" + //
                "B Y\n" + //
                "A X\n" + //
                "C X\n" + //
                "C Z\n" + //
                "B Y\n" + //
                "A Z\n" + //
                "B Y\n" + //
                "C Y\n" + //
                "C Y\n" + //
                "B Z\n" + //
                "C Y\n" + //
                "C X\n" + //
                "B Z\n" + //
                "C Y\n" + //
                "B Y\n" + //
                "B Z\n" + //
                "A Z\n" + //
                "B Z\n" + //
                "B Z\n" + //
                "B Y\n" + //
                "A Z\n" + //
                "A Y\n" + //
                "C X\n" + //
                "B Y\n" + //
                "A Z\n" + //
                "C Y\n" + //
                "B Z\n" + //
                "A Z\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "C Y\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "C Y\n" + //
                "B X\n" + //
                "B Y\n" + //
                "A X\n" + //
                "A X\n" + //
                "B Z\n" + //
                "A X\n" + //
                "C Y\n" + //
                "A Z\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "B Z\n" + //
                "A Z\n" + //
                "C Y\n" + //
                "C X\n" + //
                "B Y\n" + //
                "A Z\n" + //
                "A X\n" + //
                "B Y\n" + //
                "C X\n" + //
                "B Z\n" + //
                "A X\n" + //
                "C X\n" + //
                "B Z\n" + //
                "B Z\n" + //
                "B Z\n" + //
                "B X\n" + //
                "A X\n" + //
                "C Z\n" + //
                "C X\n" + //
                "C Z\n" + //
                "B X\n" + //
                "A Z\n" + //
                "C X\n" + //
                "B Y\n" + //
                "C X\n" + //
                "C Y\n" + //
                "C Y\n" + //
                "B Y\n" + //
                "B Z\n" + //
                "B Y\n" + //
                "C Y\n" + //
                "C X\n" + //
                "A Z\n" + //
                "C Y\n" + //
                "C Y\n" + //
                "C Y\n" + //
                "B Z\n" + //
                "A Z\n" + //
                "A Y\n" + //
                "C X\n" + //
                "C Y\n" + //
                "B Y\n" + //
                "C Y\n" + //
                "C Y\n" + //
                "B Z\n" + //
                "C Y\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "C X\n" + //
                "B Z\n" + //
                "B Y\n" + //
                "A X\n" + //
                "B Y\n" + //
                "A Z\n" + //
                "B Y\n" + //
                "C X\n" + //
                "B Y\n" + //
                "C X\n" + //
                "B Y\n" + //
                "A Z\n" + //
                "C X\n" + //
                "B Y\n" + //
                "C X\n" + //
                "B Z\n" + //
                "C X\n" + //
                "B Y\n" + //
                "A X\n" + //
                "C X\n" + //
                "C X\n" + //
                "A X\n" + //
                "C Y\n" + //
                "A Z\n" + //
                "C Y\n" + //
                "B Z\n" + //
                "A Z\n" + //
                "A X\n" + //
                "C X\n" + //
                "A X\n" + //
                "C Y\n" + //
                "A X\n" + //
                "A X\n" + //
                "B Z\n" + //
                "C X\n" + //
                "C Y\n" + //
                "A Y\n" + //
                "B Z\n" + //
                "B Y\n" + //
                "C Y\n" + //
                "B Y\n" + //
                "A Y\n" + //
                "C Y\n" + //
                "C Y\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "B Z\n" + //
                "B Z\n" + //
                "C X\n" + //
                "B Y\n" + //
                "C X\n" + //
                "A X\n" + //
                "A Z\n" + //
                "C Y\n" + //
                "B Z\n" + //
                "C Y\n" + //
                "B Y\n" + //
                "C X\n" + //
                "C X\n" + //
                "A Z\n" + //
                "B Z\n" + //
                "A Z\n" + //
                "C X\n" + //
                "B Y\n" + //
                "B Z\n" + //
                "C Y\n" + //
                "B Y\n" + //
                "A X\n" + //
                "A X\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "A X\n" + //
                "B Y\n" + //
                "B Z\n" + //
                "A Z\n" + //
                "A X\n" + //
                "A X\n" + //
                "B Z\n" + //
                "B Y\n" + //
                "A X\n" + //
                "B Z\n" + //
                "A Z\n" + //
                "B Y\n" + //
                "B Z\n" + //
                "B Z\n" + //
                "B Z\n" + //
                "C Y\n" + //
                "C Y\n" + //
                "A Z\n" + //
                "B Y\n" + //
                "C Y\n" + //
                "A Z\n" + //
                "C X\n" + //
                "B Z\n" + //
                "A X\n" + //
                "B X\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "C Y\n" + //
                "C Y\n" + //
                "B Z\n" + //
                "B Y\n" + //
                "A Z\n" + //
                "B Y\n" + //
                "A X\n" + //
                "B Z\n" + //
                "B Y\n" + //
                "C Z\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "C Y\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "A Y\n" + //
                "C Y\n" + //
                "A Z\n" + //
                "A Y\n" + //
                "B Z\n" + //
                "C X\n" + //
                "B Z\n" + //
                "A X\n" + //
                "A Z\n" + //
                "A X\n" + //
                "C Y\n" + //
                "A Z\n" + //
                "B Y\n" + //
                "B Z\n" + //
                "B Z\n" + //
                "C Y\n" + //
                "C Y\n" + //
                "C Y\n" + //
                "B X\n" + //
                "B Y\n" + //
                "B Z\n" + //
                "A X\n" + //
                "B Y\n" + //
                "C Y\n" + //
                "A X\n" + //
                "A X\n" + //
                "B Y\n" + //
                "C Y\n" + //
                "A Y\n" + //
                "B Z\n" + //
                "B Z\n" + //
                "B Z\n" + //
                "A Z\n" + //
                "B Y\n" + //
                "C X\n" + //
                "A Z\n" + //
                "C Y\n" + //
                "C Y\n" + //
                "B Y\n" + //
                "C Y\n" + //
                "C Y\n" + //
                "C Y\n" + //
                "C Y\n" + //
                "B Y\n" + //
                "B Z\n" + //
                "A Z\n" + //
                "B X\n" + //
                "C Y\n" + //
                "C X\n" + //
                "C X\n" + //
                "C Y\n" + //
                "A Z\n" + //
                "C Y\n" + //
                "C X\n" + //
                "B Z\n" + //
                "B Y\n" + //
                "A Y\n" + //
                "C Z\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "C Y\n" + //
                "B Y\n" + //
                "C Y\n" + //
                "A Z\n" + //
                "B Y\n" + //
                "C X\n" + //
                "C Y\n" + //
                "B Z\n" + //
                "A X\n" + //
                "C Y\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "A Z\n" + //
                "A X\n" + //
                "A X\n" + //
                "C X\n" + //
                "C Z\n" + //
                "B Z\n" + //
                "A X\n" + //
                "A Z\n" + //
                "A X\n" + //
                "A Y\n" + //
                "C Y\n" + //
                "C Y\n" + //
                "A Z\n" + //
                "C X\n" + //
                "C X\n" + //
                "B X\n" + //
                "B Y\n" + //
                "A X\n" + //
                "A Z\n" + //
                "A X\n" + //
                "C Y\n" + //
                "B X\n" + //
                "A X\n" + //
                "A X\n" + //
                "C X\n" + //
                "A Y\n" + //
                "B Z\n" + //
                "A Z\n" + //
                "B Y\n" + //
                "A X\n" + //
                "A Z\n" + //
                "B Y\n" + //
                "A Z\n" + //
                "C Y\n" + //
                "B Z\n" + //
                "A Z\n" + //
                "C Y\n" + //
                "C X\n" + //
                "B Z\n" + //
                "C Y\n" + //
                "B Y\n" + //
                "C X\n" + //
                "A Z\n" + //
                "B Z\n" + //
                "A X\n" + //
                "A X\n" + //
                "C Z\n" + //
                "A X\n" + //
                "C X\n" + //
                "B Y\n" + //
                "B Z\n" + //
                "A X\n" + //
                "A X\n" + //
                "C Y\n" + //
                "A Z\n" + //
                "C Y\n" + //
                "C X\n" + //
                "C Y\n" + //
                "B Z\n" + //
                "B Y\n" + //
                "C X\n" + //
                "C X\n" + //
                "B Z\n" + //
                "B Z\n" + //
                "C Y\n" + //
                "A X\n" + //
                "B X\n" + //
                "C X\n" + //
                "C Y\n" + //
                "A X\n" + //
                "A Z\n" + //
                "B Y\n" + //
                "C X\n" + //
                "A Y\n" + //
                "C X\n" + //
                "C Y\n" + //
                "A Z\n" + //
                "B Y\n" + //
                "B Z\n" + //
                "B Y\n" + //
                "C X\n" + //
                "C Y\n" + //
                "C X\n" + //
                "C X\n" + //
                "B Y\n" + //
                "C X\n" + //
                "C X\n" + //
                "B Y\n" + //
                "C Z\n" + //
                "C Y\n" + //
                "C Y\n" + //
                "B Z\n" + //
                "B Z\n" + //
                "B Y\n" + //
                "A X\n" + //
                "B Y\n" + //
                "A Z\n" + //
                "A Y\n" + //
                "B Y\n" + //
                "C Y\n" + //
                "B Z\n" + //
                "B Z\n" + //
                "A X\n" + //
                "B Y\n" + //
                "A X\n" + //
                "B Y\n" + //
                "A Z\n" + //
                "B Y\n" + //
                "C X\n" + //
                "A Z\n" + //
                "B Z\n" + //
                "C Y\n" + //
                "B Y\n" + //
                "A Y\n" + //
                "A X\n" + //
                "C X\n" + //
                "A X\n" + //
                "B Y\n" + //
                "B Z\n" + //
                "B Z\n" + //
                "C Y\n" + //
                "A X\n" + //
                "B Y\n" + //
                "B Z\n" + //
                "B Y\n" + //
                "B X\n" + //
                "C Z\n" + //
                "B Z\n" + //
                "C X\n" + //
                "C Y\n" + //
                "C X\n" + //
                "B Z\n" + //
                "C Y\n" + //
                "A X\n" + //
                "A X\n" + //
                "C X\n" + //
                "B Y\n" + //
                "B X\n" + //
                "B Y\n" + //
                "A X\n" + //
                "C Y\n" + //
                "A Z\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "B Y\n" + //
                "B Z\n" + //
                "B Y\n" + //
                "C X\n" + //
                "A Z\n" + //
                "C Y\n" + //
                "A Z\n" + //
                "B Z\n" + //
                "C X\n" + //
                "C Y\n" + //
                "C X\n" + //
                "C Y\n" + //
                "A Y\n" + //
                "B Z\n" + //
                "B Y\n" + //
                "B Z\n" + //
                "C Y\n" + //
                "A X\n" + //
                "B Y\n" + //
                "A X\n" + //
                "C X\n" + //
                "B X\n" + //
                "C X\n" + //
                "A Z\n" + //
                "B Z\n" + //
                "B Z\n" + //
                "C Y\n" + //
                "B Z";
    }
}